version: '3.3'

services:
  registry:
    image: registry:2
    ports:
      - "5000:5000"
    environment:
      REGISTRY_AUTH: htpasswd
      REGISTRY_AUTH_HTPASSWD_REALM: "Registry Realm"
      REGISTRY_AUTH_HTPASSWD_PATH: /auth/htpasswd
    volumes:
      - ./auth:/auth   # dossier local où se trouve le fichier htpasswd
      - registry-data:/var/lib/registry
    restart: always

  app:
    image: localhost:5000/express_app:latest
    restart: always
    volumes:
      - /var/log/microservice:/app/logs
    networks:
      - internal_net

nginx:
  image: nginx:latest
  ports:
    - "85:80"
  volumes:
    - ./nginx.conf:/etc/nginx/nginx.conf:ro
  depends_on:
    - app
  networks:
    - internal_net

volumes:
  registry-data:

networks:
  internal_net:
    driver: bridge

